# Generated by Django 2.2.2 on 2019-06-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('points_accrued', models.FloatField(default=0)),
                ('points_used', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSeniority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('seniority', models.CharField(max_length=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accrualapp.Employee')),
            ],
        ),
    ]
