# Generated by Django 2.2.2 on 2019-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accrualapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniority', models.CharField(max_length=1)),
                ('points_per_month', models.IntegerField()),
            ],
        ),
    ]
